### ISSUE TITLE
Number not parsed

### ISSUE THREAD

**Issue by jwiegley** [LeventErkok/FloatingHex#6]
```
Prelude Data.Numbers.FloatingHex> readHFloat "0xa0ff.f141a59a"
Nothing

> :set -XHexFloatLiterals
> toRational (0xa0ff.f141a59a :: Double) == 0xa0ff.f141a59a
True
```

**Comment by LeventErkok** [comment]
`FloatingHex` follows the spec more closely, see page 57 of http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf

To wit: 

```
$ cat a.c
#include <stdio.h>

int main(void)
{
    printf("%f\n", 0xa0ff.f141a59a);
    return 0;
}

$ make a
cc     a.c   -o a
a.c:5:35: error: hexadecimal floating constant requires an exponent
    printf("%f\n", 0xa0ff.f141a59a);
                                  ^
1 error generated.
make: *** [a] Error 1
```

So, strictly speaking GHC is violating the spec. The reason the standard requires the `p` part is to avoid ambiguity with the optional suffix part that we're already ignoring; so I think being liberal there doesn't really hurt.

Is this causing an issue? Since `HexFloatLiterals` made it into GHC, I consider this library to be more or less redundant. (The library was written before the GHC addition.)

**Comment by jwiegley** [comment]
I see, it's not a bug in the library then. I'm using it to parse hexadecimal floats out of WebAssembly source files. I can just append "p0" and try again whenever it fails. Thanks!

**Comment by LeventErkok** [comment]
I’m not opposed to relaxing the parser here, it would be a trivial change. Let me know if it causes performance/convenience issues on your side to call twice, and I’d be happy to make a new release.
